### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by domdomegg**
Provide instructions for enabling Maven Integration from the Quick Start menu on Android Studio 1.5

### CODE REVIEW

**Comment by misaochan** [comment]
Thanks @domdomegg !

**Comment by misaochan** [comment]
Ah, do you want to reopen the pull request? I think the modification is good.

**Comment by domdomegg** [comment]
The instructions don't seem to work past step 13, I've been messing around with android studio for a while trying to get it to work to no avail. I'll report back with progress or if you can check step 13 and see if I'm doing anything wrong I'd be grateful. Currently a load of other errors turn up but nowhere is there ``import android.support.v4.app.FragmentActivity``

**Comment by misaochan** [comment]
Could you try to do steps 14-16 even though you don't see that line, and see if that works?

**Comment by domdomegg** [comment]
Yeah, I've tried that yet it still gave me a load of errors. Can't remember them atm, but my computer currently seems to be intent on converting it all to gradle...

**Comment by misaochan** [comment]
Yeah, sorry, this project is a little messy, lots of it is legacy code and it uses Maven, which is a different build tool from Gradle. Android Studio usually asks me if I want to convert to Gradle, and I have the option to say 'no'. We have been talking for a while about converting it to Gradle, but that's likely to be quite a herculean task...

**Comment by domdomegg** [comment]
Yeah, tried maven as well, I'll try again now and see if I can send you the error messages

**Comment by misaochan** [comment]
Sure thing. Have to head off now, but will check back tomorrow. If it helps, I don't usually have to do Step 13 in Android Studio.

**Comment by domdomegg** [comment]
Sure.

Cya, for tomorrow these are the steps / settings:
https://imgur.com/a/iH2zT

**Comment by domdomegg** [comment]
Yay! Finally got it working (don't worry, I haven't been working 5 hours straight on this :P)

So:
Follow instructions up to step 12
In Project Structure > Modules and for each Dependencies > Module SDK:
commons -> Maven Android API 23 Platform
~apklib-com.actionbarsherlock_actionbarsherlock_4.4.0 -> Maven Android API 14 Platform
~apklib-com.viewpagerindicator_library_2.4.1 -> Maven Android API 16 Platform
In Porject Structure > Modules and for each Sources > Language level:
Project default (8 - Lambdas, type annotations etc.)
You can set the default on the sidebar (Project > Project language level), idk why but for me this was set to random different ones which screwed up some things.

I need to test this again to check this is actually what I have done, because it's possible I did other stuff which fixed it.

(This needs to be better written and then put into the guide, I'll probably do it later)

**Comment by domdomegg** [comment]
Before doing the stuff above, you need to go to File > Settings > Java compiler
set everything to version 1.8

this doesn't work if you do it afterwards as all the APIs and java versions will reset idk why

**Comment by misaochan** [comment]
Interesting! Mine was always set to 1.8 (and language level 8) as default, but definitely worth noting this, nice work.

**Pull request closed without merging**
