### PR TITLE
Fix permissions on API levels 23 and above

### PR DESCRIPTION
**Pull request by domdomegg**
The most significant and relevant changes are in ShareActivity.java

Also I've found (I'm not sure how) but the app is happy to upload the image without any permissions so it has to be reading it from somewhere. Because of this the current implementation is to provide an option to the user via a snackbar to additionally give storage+location permissions, which allows the app to extract extra metadata when uploading. What's strange is that it must be possible without these permissions as a test upload I did included all the EXIF data when I gave the app no permissions, so we could change to extract it out of that.

However we should consider if we want to force the user to give storage rights as otherwise often (it seems a bit random) the date is not added. Alternatively we could supply a date field?

Also I have tested this on my phone (running 6.0.1), and a range of emulators however I don't have a physical device with API<=20 to test it on atm, so it would be good if someone could check before this is merged :)

Also fixed a very small bug when testing, so incorrect password error is correctly recognised (WrongPluginPass).

EDIT - meant API <= 22

### CODE REVIEW

**Comment by misaochan** [comment]
Hmm, my phone is API 21 (5.0.1) unfortunately. :/ Sorry if this is a silly question, but why the specific need for API <= 20?

**Comment by misaochan** [comment]
Love the snackbar option. Tested this on an API 23 emulator and received this error after submitting a photo (past the categorization screen). I guess we need to check permissions for this as well? Odd that I have not received this error before though.

```
06-09 17:39:43.656: E/ACRA(2685): fr.free.nrw.commons fatal error : Unable to pause activity {fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void fr.free.nrw.commons.upload.GPSExtractor.unregisterLocationManager()' on a null object reference
06-09 17:39:43.656: E/ACRA(2685): java.lang.RuntimeException: Unable to pause activity {fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void fr.free.nrw.commons.upload.GPSExtractor.unregisterLocationManager()' on a null object reference
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.ActivityThread.-wrap13(ActivityThread.java)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
06-09 17:39:43.656: E/ACRA(2685): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-09 17:39:43.656: E/ACRA(2685): 	at android.os.Looper.loop(Looper.java:148)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-09 17:39:43.656: E/ACRA(2685): 	at java.lang.reflect.Method.invoke(Native Method)
06-09 17:39:43.656: E/ACRA(2685): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-09 17:39:43.656: E/ACRA(2685): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-09 17:39:43.656: E/ACRA(2685): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void fr.free.nrw.commons.upload.GPSExtractor.unregisterLocationManager()' on a null object reference
06-09 17:39:43.656: E/ACRA(2685): 	at fr.free.nrw.commons.upload.ShareActivity.onPause(ShareActivity.java:312)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.Activity.performPause(Activity.java:6348)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
06-09 17:39:43.656: E/ACRA(2685): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
06-09 17:39:43.656: E/ACRA(2685): 	... 10 more

```

**Comment by domdomegg** [comment]
Just wanted to test on <= 20 in case I broke something there by accident, with all my if statements excluding API <= 20 :)

I will have a look at that error later today, I need to go now. Maybe try changing the whole if statement in 310 to imageObj != null? Not sure, will test later anyway.

Also looking around it looks like we could easily extract location from exif without location services (see GPSExtractor's getCoords() method).

**Comment by nicolas-raoul** [comment]
I believe we only use location services if the picture file does not contain EXIF coordinates.

**Comment by misaochan** [comment]
Yeah, getCoords() only works if the user has enabled geotagging in their camera. There is an option whereby they can elect to 'use current location' if they don't want to use camera geotagging, that is where location services come in.

**Comment by misaochan** [comment]
The != null fix does work on my API 23 emulator, but please do test on a real device as well (I don't have one with API 23).

**Comment by domdomegg** [comment]
Whoops I think I'm going crazy.. I meant <= 22, not 20.

Yeah I didn't check != null myself, just a thought. Will try to find a fix now.

Perhaps we should leave out the date or use the upload date if it's 1970-0-01 (start of unix time, and it's very unlikely people will be uploading photos taken then with the app).

I'll see if I can put getCoords() outside the main GPS method or ask for permissions if it is not found...

**Comment by misaochan** [comment]
Ah, that explains the 1970! I don't think we can just leave out the date, although it's tempting as it would be the easiest fix :D (@nicolas-raoul what do you think?).

**Comment by misaochan** [comment]
I won't be around this weekend to help test unfortunately, but if still needed I can run your latest code on my API 21 real device on Monday. If all works well maybe I'll do another release then, since this is a pretty big bug. :)

**Comment by domdomegg** [comment]
Cool :)

**Comment by nicolas-raoul** [comment]
> leave out the date or use the upload date if it's 1970-01-01

Yeah upload time is definitely better :-)

Commons people won't touch 1970-01-01 dates because it could actually be the true date, but as a smartphone app we don't have to care about this possibility I think.

**Comment by domdomegg** [comment]
It now catches a NPE but it would be better to be able to extract the location without location permission, and only ask for location permission if image does not have location data, will sort that out before merge

**Comment by domdomegg** [comment]
Now have fixed the location permissions being requested when they are not really needed. Not sure if the date problem is related, may be something to do with storage permission but not 100% sure yet.

**Comment by domdomegg** [comment]
See #123 for a date fix

**Comment by domdomegg** [comment]
I *think* this is ready to merge, but please do test it :)

**Comment by misaochan** [comment]
Thanks @domdomegg ! I don't have access to Android Studio at the moment, will be back on Monday. :)

**Comment by misaochan** [comment]
Hi @domdomegg ,

I've tested the current build with my API 21 real device and am getting this error as soon as I try to launch the app:

`06-12 23:51:53.215: E/ACRA(15831): ACRA caught a RuntimeException exception for fr.free.nrw.commons. Building report.
06-12 23:51:53.295: E/ACRA(15831): fr.free.nrw.commons fatal error : Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.ContributionsActivity}: java.lang.SecurityException: caller uid 10292 lacks any of android.permission.GET_ACCOUNTS
06-12 23:51:53.295: E/ACRA(15831): java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.contributions.ContributionsActivity}: java.lang.SecurityException: caller uid 10292 lacks any of android.permission.GET_ACCOUNTS
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
06-12 23:51:53.295: E/ACRA(15831): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-12 23:51:53.295: E/ACRA(15831): 	at android.os.Looper.loop(Looper.java:145)
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
06-12 23:51:53.295: E/ACRA(15831): 	at java.lang.reflect.Method.invoke(Native Method)
06-12 23:51:53.295: E/ACRA(15831): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-12 23:51:53.295: E/ACRA(15831): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
06-12 23:51:53.295: E/ACRA(15831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
06-12 23:51:53.295: E/ACRA(15831): Caused by: java.lang.SecurityException: caller uid 10292 lacks any of android.permission.GET_ACCOUNTS
06-12 23:51:53.295: E/ACRA(15831): 	at android.os.Parcel.readException(Parcel.java:1540)
06-12 23:51:53.295: E/ACRA(15831): 	at android.os.Parcel.readException(Parcel.java:1493)
06-12 23:51:53.295: E/ACRA(15831): 	at android.accounts.IAccountManager$Stub$Proxy.getAccountsAsUser(IAccountManager.java:746)
06-12 23:51:53.295: E/ACRA(15831): 	at android.accounts.AccountManager.getAccountsByTypeAsUser(AccountManager.java:497)
06-12 23:51:53.295: E/ACRA(15831): 	at android.accounts.AccountManager.getAccountsByType(AccountManager.java:491)
06-12 23:51:53.295: E/ACRA(15831): 	at fr.free.nrw.commons.CommonsApplication.getCurrentAccount(CommonsApplication.java:186)
06-12 23:51:53.295: E/ACRA(15831): 	at fr.free.nrw.commons.auth.AuthenticatedActivity.requestAuthToken(AuthenticatedActivity.java:115)
06-12 23:51:53.295: E/ACRA(15831): 	at fr.free.nrw.commons.contributions.ContributionsActivity.onCreate(ContributionsActivity.java:133)
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.Activity.performCreate(Activity.java:6289)
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
06-12 23:51:53.295: E/ACRA(15831): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
06-12 23:51:53.295: E/ACRA(15831): 	... 10 more
`

**Comment by misaochan** [comment]
Same issue on an API 21 emulator. Are you able to run it without crashing on your emulator?

**Comment by misaochan** [comment]
Putting the user-permission lines you removed in the Manifest solves the issue. Is there a reason they need to be removed?

**Comment by domdomegg** [comment]
I did change the permissions in the manifest, I think that must be it. Maybe it's not backwards compatible, as on 23+ you don't need GET_ACCOUNTS permission to access accounts created by your app. I think if I add it back and try again it should be fine on both without a permission req on 23+. Need to test, I'll be home later

**Comment by domdomegg** [comment]
Wow I'm just underground and just wrote that, good timing :P

**Comment by misaochan** [comment]
Haha, sweet. :) I'll merge when you can confirm it works on your API 23 real device.

**Comment by domdomegg** [comment]
Yep tested on API 23, all seems good.

**Comment by misaochan** [comment]
Thanks!

**Comment by misaochan** [comment]
@domdomegg , would you like to be added to the credits? :) I can put your name in if you do.

**Comment by domdomegg** [comment]
Yeah ok :)

I don't mind either domdomegg / Adam Jones

**Comment by misaochan** [comment]
All done. :)

**Pull request merged**
