### PR TITLE
Fix crash if FileNotFound exception thrown

### PR DESCRIPTION
**Pull request by misaochan**

### CODE REVIEW

**Comment by misaochan** [comment]
@nicolas-raoul on a slightly related note, do we want to announce on mailing lists that the app name and logo have changed? I guess most people will be able to deduce that, but a few might be confused and wonder where 'Upload to Commons' went. :)

Also, why does it say 'we are not endorsed by or affiliated with WMF' on the front page, when the ownership of the app will soon go to the WMF account? Or is that line just there until the ownership transfer completes?

**Comment by nicolas-raoul** [comment]
A announcement would be good indeed!

**Comment by nicolas-raoul** [comment]
The wording comes from the contract thread I forwarded to you, it is in the
About dialog too.

**Comment by misaochan** [comment]
Ah, okay, sweet. I'll try to get word out to the mailing lists tomorrow. :) Is this PR ok to merge, btw?

**Pull request merged**
