### PR TITLE
Rebranded using Wikimedia logo and name, as authorized by contract si…

### PR DESCRIPTION
**Pull request by nicolas-raoul**
…gned between me and WIKIMEDIA FOUNDATION INC's Charles M. Roslof

### CODE REVIEW

**Comment by nicolas-raoul** [comment]
@misaochan I let you review and merge :-)

**Comment by misaochan** [comment]
Woo, looks great! :) When will the Google Play change in account go through?

**Comment by nicolas-raoul** [comment]
I don't know when the account will be transferred, probably when they find the right person and this person gets time, I guess.
For now we can continue publishing to the non-transferred account.

**Comment by misaochan** [comment]
Okay, sure.

**Comment by misaochan** [comment]
Is it okay for us to use this logo/trademark before the change of ownership goes through? I've been planning to release the new updates and not sure if I should upload the APK with or without the new logo.

**Comment by nicolas-raoul** [comment]
Yes, it is OK. Please use the new logo for all releases from now on :-)

**Comment by misaochan** [comment]
Okay, uploaded new APK :)

**Comment by misaochan** [comment]
Got this message on Google Play: 

Your recent app submission was rejected for violating the Impersonation and Intellectual Property policy. Before submitting your app for another review, read through the Impersonation section of the policy and modify your app title so that it doesn't imply an official relationship with an existing product or service. If you submitted an update, the previous version of your app is still live on Google Play.

**Comment by nicolas-raoul** [comment]
Could you please send me a screenshot? I will forward it to WMF. Thanks!

**Comment by nicolas-raoul** [comment]
You can also send them the contract I fowarded to you, if they have somewhere to send this kind of things.

**Comment by misaochan** [comment]
They haven't posted any contact info, but they said that they would send an email to you. Maybe you could respond if it isn't a noreply address?

googleplay_error

**Comment by nicolas-raoul** [comment]
Thanks! I have sent the contract to https://support.google.com/googleplay/android-developer/troubleshooter/2993242
If we don't have an answer from them within a week let's advise then, but for now let's not worry too much about it, and just create a branch without the new name/logo.

**Comment by misaochan** [comment]
Ah, so probably revert this merge for now?

**Comment by nicolas-raoul** [comment]
Yes, branch and revert that particular commit, thanks!

**Comment by misaochan** [comment]
Error: "Cannot revert merge commit". Apparently the solution is to revert -m to a specific parent, but which parent do we want to revert to?

**Comment by nicolas-raoul** [comment]
I reverted in this branch:
https://github.com/nicolas-raoul/apps-android-commons/tree/nobrand

**Comment by nicolas-raoul** [comment]
Now the app has been suspended, great :-/
Not sure if this decision has been taken because they have not received the contract yet, or because they have received it and decided to ignore it. Let's give them the cited two business days before further action.

**Comment by nicolas-raoul** [comment]
Looks like another incentive to publish the app on F-Droid.

**Comment by misaochan** [comment]
Ugh, okay. Do you think it might have to do with the fact that I tried to upload the nobrand version today? I thought it would be okay since it was using our old name and title.

**Comment by nicolas-raoul** [comment]
I have sent an email to WMF explaining the suspension, the IEG timing, and asking them to call Google.

I think the problem was that even though the APK was OK, the market details (include name and logo) were still branded as WMF.

**Comment by misaochan** [comment]
Ah, okay. Thanks Nicolas!

**Pull request merged**
