### PR TITLE
Remove campaigns

### PR DESCRIPTION
**Pull request by misaochan**
Attempt at fixing issue #13. This is done in 2 stages:
1. Just removing Campaigns from AndroidManifest.xml (to prevent creation of campaigns shortcut)
2. Removing dead code & reformatting code (to fix spacing)

I am confident about the first commit but not so much about the second. It worked fine on the Android emulator that I tested it on, but I hope you can glance at the code to test that I didn't break anything. Further details are on the commit itself.

### CODE REVIEW

**Comment by misaochan** [comment]
I have pushed the commit to fix the semicolon. 

Thanks for linking me to the use of formatting rules. :) Shall we use Checkstyle for this project? Or if we are all using IntelliJ (and I think for Android dev we all have to use the same IDE since otherwise the file structure will change each time a different person pushes to this repo?) can we just rely on the default IntelliJ formatting style being the same?

**Comment by nicolas-raoul** [comment]
I don't use IntelliJ, actually I don't use an IDE at all, I use gradle and
vim from command line, and sometimes Eclipse. All IDEs can adapt to any
file structure. Actually the structure we use currently is the Gradle
standard.
How about we adopt your current formatting rules as our formatting
standard? There is probably a way to export your formatting rules from your
IDE as a file and put it in Git.

**Comment by misaochan** [comment]
Oh, okay! I'm not sure why, but I read in the Android Studio documentation that the file structure will change if we import a project there, that's why I stuck with IntelliJ. But I probably am missing something there. 

I will try to figure out how to export the current formatting rules. :)

**Comment by misaochan** [comment]
Unfortunately I'm still struggling to export the code style settings. :( I posted a thread detailing my problems at http://stackoverflow.com/questions/33258033/exporting-code-style-settings-from-intellij-idea-version-14-1-5 so hopefully I will get some answers soon.

**Comment by nicolas-raoul** [comment]
It is not quite low-priority so don't worry too much...

**Comment by misaochan** [comment]
I've found out how to export the code style settings as an XML file, but it will only state the differences to the default code style settings in IntelliJ, so it will only be useful if the other devs use IntelliJ. I've been told that there is apparently no innate way to export code style settings from IntelliJ to be used across different IDEs. But we can use a 3rd party plugin like EditorConfig if we want to do that.

**Comment by misaochan** [comment]
Hmm. When I tested on my real device (Galaxy S4) I discovered a bug where after I upload a new image, every alternate image in the 'My Uploads' page turns into that image. :/ Unfortunately I can't tell for sure if that was caused by the code changed in this branch, or if that bug already existed before (since there were several existing bugs with displaying uploaded images). Looking at my code in this pull request, I can't see anything I might have done to cause this, but I might be missing something. Should I revert the 'removing dead code' commit?

**Comment by nicolas-raoul** [comment]
With all the style changes it's a bit hard to have a general view (tip: Adding ?w=1 at the end of the URL makes Github ignore whitespace at least), but I don't see any obvious culprit.

Please try the version just before that commit and check whether the bug was already present or not. Maybe the bug happens randomly, in which case several tests will be necessary.

**Comment by misaochan** [comment]
After multiple tests I've concluded that the 'remove dead code' commit is definitely the problem. The My Uploads page works fine after I reverted that commit.

Shall I upload to Google Play first with just the campaigns shortcut removed, and only later try to wrangle with this bug?

**Comment by nicolas-raoul** [comment]
How about starting a new branch `remove-campaigns2` and removing things one-by-one, without the giant reformatting, so that we can see the changes very clearly?

That would also help in the future when comparing the with old versions from last year for instance.

**Comment by misaochan** [comment]
Whoops, I just found after even more testing that this bug occasionally occurs with all versions of the app including the one currently on Google Play from September.... which is odd, since I hadn't noticed it happening before. I'm quite confused... maybe I'll make an issue for it.

I will also still start a new branch and do the commit properly without the reformat, as it'll be tidier anyway.

**Comment by nicolas-raoul** [comment]
Good find!
Would you mind creating a new issue describing the problem, the version with which it happened, and maybe a screenshot?
Thanks! :-)

**Comment by misaochan** [comment]
Bug is discussed further in issue #25

**Comment by misaochan** [comment]
I have submitted a new pull request #26 with small, modular commits (and no reformat!). It's a branch off of this branch, so it also has all the changes made in this one. I think this pull request is probably redundant now, shall I close it?

**Comment by nicolas-raoul** [comment]
All included commits have been merged by #26, so Github closed this one automatically it seems.
Thanks! :-)

**Pull request merged**
