### PR TITLE
Migrating to gradle

### PR DESCRIPTION
**Pull request by domdomegg**
I have no experience manually migrating projects from maven to gradle, so you should definitely check this before merging. I've tested it for a while, seems fine but it would be good to double check! :)

### CODE REVIEW

**Comment by misaochan** [comment]
I'll try to build this and see if it works, will get back to you. There appear to be merge conflicts though?

**Comment by domdomegg** [comment]
The merge conflicts occur as the translation files have just been merged, I'll see if I can sort it out

**Comment by nicolas-raoul** [comment]
Ah sorry I just merged the easy (and urgent) one first before studying the others...

**Comment by misaochan** [comment]
Hmm, I followed the steps in your new README.md and received the error: `Error:Android Source Generator: [apps-android-commons-master] AndroidManifest.xml file not found`

This is odd though, as I can see the AndroidManifest.xml in the project structure.

**Comment by domdomegg** [comment]
Nah don't worry, I don't think there are really any merge conflicts, but git wants to throw them up anyway, but just checking now

**Comment by domdomegg** [comment]
Are you using Android Studio 2.1?

Are you sure you selected the 'commons' folder not the 'apps-android-commons' (as it was with maven)?

**Comment by misaochan** [comment]
Ah, yes, sorry, got confused with that. Using 'commons' folder solves that problem, building now. :)

**Comment by domdomegg** [comment]
excellent ;)

**Comment by misaochan** [comment]
There are ABS errors, but we will be wanting to use https://github.com/nicolas-raoul/apps-android-commons/pull/115 over this, so shouldn't matter, right?

**Comment by domdomegg** [comment]
Yeah, but there shouldn't be ABS errors :/

Maybe check #115 instead so we can merge it in one go?

**Comment by domdomegg** [comment]
What errors are you getting?

**Comment by misaochan** [comment]
```
Error:Error: File path too long on Windows, keep below 240 characters : C:\Downloads\domdomegg-apps-android-commons-master\apps-android-commons-master\commons\app\build\intermediates\exploded-aar\com.actionbarsherlock\actionbarsherlock\4.4.0\res\drawable-xhdpi\abs__textfield_search_right_selected_holo_light.9.png
:app:mergeDebugResources FAILED
Error:Execution failed for task ':app:mergeDebugResources'.
> C:\Downloads\domdomegg-apps-android-commons-master\apps-android-commons-master\commons\app\build\intermediates\exploded-aar\com.actionbarsherlock\actionbarsherlock\4.4.0\res\drawable-xhdpi\abs__textfield_search_right_selected_holo_light.9.png: Error: File path too long on Windows, keep below 240 characters : C:\Downloads\domdomegg-apps-android-commons-master\apps-android-commons-master\commons\app\build\intermediates\exploded-aar\com.actionbarsherlock\actionbarsherlock\4.4.0\res\drawable-xhdpi\abs__textfield_search_right_selected_holo_light.9.png
```

I'll check #115

**Comment by misaochan** [comment]
Well, I should be able to fix that by changing the folder name... but I think my folder name wasn't much longer than the norm. :)

**Comment by domdomegg** [comment]
There's a file path maximum length?!

Yeah good idea, currently it's just at 242 but surprised it just breaks with 240+ characters

**Comment by misaochan** [comment]
```
06-06 19:02:55.068: E/AndroidRuntime(3719): java.lang.RuntimeException: Unable to get provider fr.free.nrw.commons.contributions.ContributionsContentProvider: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to fr.free.nrw.commons.CommonsApplication
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.os.Looper.loop(Looper.java:148)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at java.lang.reflect.Method.invoke(Native Method)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-06 19:02:55.068: E/AndroidRuntime(3719): Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to fr.free.nrw.commons.CommonsApplication
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at fr.free.nrw.commons.contributions.ContributionsContentProvider.onCreate(ContributionsContentProvider.java:37)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
06-06 19:02:55.068: E/AndroidRuntime(3719): 	... 10 more

```

**Comment by domdomegg** [comment]
Strange, I don't get that error :/

Were you doing something specific when you got that error message? Android Studio does warn me on that line than it might cause a NullPointerException, but not a ClassCastException

**Comment by misaochan** [comment]
No, happens as soon as the app launches. I don't even get to the welcome screen :/

**Comment by domdomegg** [comment]
That's really strange, no idea what's happening there.

Are you using this pr (my master branch) or the ABS-removal one or the email-fix one?

**Comment by misaochan** [comment]
I cloned your master branch.

**Comment by domdomegg** [comment]
I think it's caused by instant run in Android Studio, can you try turning it off and see if it works?

**Comment by domdomegg** [comment]
(File > Settings > Build, Execution, Deployment > Instant Run > "Enable Instant Run to hot swap code/resource changes on deploy")

**Comment by domdomegg** [comment]
Just as I was messing about with it I managed to find a new bug, which is that for some reason only on my phone (not emulator) uploading an image from the gallery does not work (as android 23 requires the app to [request permissions](https://developer.android.com/training/permissions/requesting.html)).

**Comment by misaochan** [comment]
Oh, hey, it does work for me now. :) Have to go soon, but will try to check it a bit more later. Haven't tried the manual build though.

**Comment by domdomegg** [comment]
Cool :)

**Comment by domdomegg** [comment]
I'll also add that you need instant run off to the README.md

**Comment by misaochan** [comment]
Thanks @domdomegg !

**Comment by domdomegg** [comment]
np :)

**Comment by domdomegg** [comment]
I'll open a new issue about permissions though

**Comment by misaochan** [comment]
Yes, please do.

**Pull request merged**
